
services:
  db:
    container_name: 'users-db'
    image: mcr.microsoft.com/mssql/server
    ports:
        - "1434:1433"
    environment:
        SA_PASSWORD: "rootR12345678!"
        ACCEPT_EULA: "Y"
        MSSQL_PID: "Express"
        MSSQL_DATABASE: "user_db"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  db2:
    container_name: 'device-db'
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1435:1433"
    environment:
      SA_PASSWORD: "rootR12345678!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      MSSQL_DATABASE: "device_db"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  db3:
    container_name: 'monitoring-db'
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1436:1433"
    environment:
      SA_PASSWORD: "rootR12345678!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      MSSQL_DATABASE: "dataDevice_db"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  users-app-backend:
    depends_on:
      - db
    container_name: users-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      TZ: "UTC"
      MICROSERVICE_NAME: "devices-backend"
      DB_IP: "users-db"
      DB_USER: "sa"
      DB_PASSWORD: "rootR12345678!"
      DB_PORT: "1433"
      DB_NAME: "user_db"
    ports:
      - "8081:8081"
    expose:
      - "8081"
  devices-app-bakend:
    depends_on:
      - db2
    container_name: devices-backend
    build:
      context: ../../ds2023_30641_calin_catalin_iacob_assigment_1_devicemanagement/DeviceManagement
      dockerfile: ../../ds2023_30641_calin_catalin_iacob_assigment_1_devicemanagement/DeviceManagement/Dockerfile
    environment:
      DB_IP: "device-db"
      DB_PORT: "1433"
      DB_USER: "sa"
      DB_PASSWORD: "rootR12345678!"
      DB_NAME: "device_db"
    ports:
      - "8080:8080"
    expose:
      - "8080"
  monitoring-app-bakend:
    depends_on:
      - db3
    container_name: monitoring-backend
    build:
      context: ../../ds2023_30641_calin_catalin_iacob_assigment_2_monitoringandcomunicationservice/MonitoringAndComunicationService
      dockerfile: ../../ds2023_30641_calin_catalin_iacob_assigment_2_monitoringandcomunicationservice/MonitoringAndComunicationService/Dockerfile
    environment:
      DB_IP: "monitoring-db"
      DB_PORT: "1433"
      DB_USER: "sa"
      DB_PASSWORD: "rootR12345678!"
      AllowedOrigin: "http://localhost"
    ports:
      - "8082:8082"
    expose:
      - "8082"
  frontend-app:
    container_name: frontend-user-devices-app
    build:
      context: ../../ds2023_30641_calin_catalin_iacob_assigment_1_frontend/UserDevicesApp
      dockerfile: ./Dockerfile
    hostname: energy-management
    ports:
      - "81:80"
      - "433:433"
    expose:
      - "80"
      - "433"
volumes:
  my-db: {}

networks:
  default:
    name: SD1