# The Docker image that will be used to build your app
stages:
    - build
    - deploy

variables:
    IMAGE_TAG: angular-app

build_image:
    stage: build
    image: docker:24.0.7-cli
    services:
        - docker:24.0.7-dind
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    before_script:
        - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
    script:
        - docker pull $CI_REGISTRY_IMAGE || true
        - docker build -t $CI_REGISTRY_IMAGE:$IMAGE_TAG ./UserDevicesApp
        - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG

deploy:
    stage: deploy
    before_script:
        - chmod 0400 $SSH_KEY
    script:
        - ssh -i $SSH_KEY -o StrictHostKeyChecking=no calincatalin99@34.139.55.205 "
            docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY &&
            docker stop frontend-app || true &&
            docker rm frontend-app || true &&
            docker rmi $CI_REGISTRY_IMAGE:$IMAGE_TAG || true &&
            docker pull $CI_REGISTRY_IMAGE || true &&
            docker run -d --name frontend-app -p 80:80 $CI_REGISTRY_IMAGE:$IMAGE_TAG &&
            docker network connect SD frontend-app"